// GENERATED FILE 31-01-2021 10:10:43
// This file is being generated by GenerateTypescript.cs

// == Standard declarations ======================================
export var baseUrl = ''

function timeout(millis = 300): Promise<void> {
	return new Promise<void>(function(resolve) { setTimeout(resolve, millis); });
}

async function get (url: string): Promise<any> {
	return await fetch(baseUrl + url).then(v => v.json());
}
async function post(url: string, data: any): Promise<any> {
	return await fetch(baseUrl + url, {
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		body: JSON.stringify(data)
	});
}
async function del (url: string): Promise<any> {
	return await fetch(baseUrl + url, { method: 'DELETE' });
}

// == Endpoint: PlayalongApiV1 '/api/playalong/v1/' ======================================
export
interface SongSection {
	name: string;
	start: number;
	end: number;
}

export
interface Song {
	id: string;
	title: string;
	band: string;
	bpm: number;
	startOffset: number;
	source: string;
	sections: SongSection[];
}

export function getSongs(): Promise<Song[]> { return get(`/api/playalong/v1/songs`); }
export function getSong(id: string): Promise<Song> { return get(`/api/playalong/v1/songs/${id}`); }
export function saveSong(id: string, song: Song): Promise<void> { return post(`/api/playalong/v1/songs/${id}`, song); }
export function deleteSong(id: string): Promise<void> { return del(`/api/playalong/v1/songs/${id}`); }
